# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Forum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forum
	pod 'ObjectMapper', '~> 2.2'
	pod 'SwiftyJSON', '~> 3.1'
	pod 'Kingfisher', '~> 3.10'
	pod 'Firebase'

  target 'ForumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ForumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
